# -*- coding: utf-8 -*-
"""streamlit_student_web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X5LfR7IQVt2Kvl0Te3djL2j8-X_4Uqqn
"""

import streamlit as st
import numpy as np
import sklearn

# 1. إعداد عنوان الصفحة
st.set_page_config(page_title="Educational Prediction Model", layout="wide")
st.title("🎓 تطبيق التنبؤ بأداء الطلاب")
st.write("أدخلي البيانات المطلوبة للتحقق من التنبؤ الخاص بالموديل")

# 2. تحميل الموديل (تأكدي أن الملف model.pkl في نفس المجلد)
import joblib  # 👈 تغيير مكتبة التحميل إلى joblib

# تحميل الموديل باستخدام joblib لتفادي خطأ السلسلة والنصوص في pickle
@st.cache_resource
def load_model():
    # joblib بتتعامل بشكل أفضل مع اختلاف إصدارات scikit-learn
    model = joblib.load("student_grades_RF.pkl")
    return model

try:
    model = load_model()
except Exception as e:
    st.error(f"خطأ في تحميل الموديل: {e}")
    st.stop()

# 3. واجهة إدخال البيانات (منظمة في أعمدة)
st.subheader("📋 بيانات الطالب")

col1, col2 = st.columns(2)

with col1:
    gender = st.selectbox("الجنس (Gender)", ["Male", "Female"])
    raisedhands = st.number_input("عدد مرات رفع اليد (raisedhands)", min_value=0, max_value=100, value=10)
    visited_resources = st.number_input("زيارة المصادر (VisITedResources)", min_value=0, max_value=100, value=10)
    announcements_view = st.number_input("رؤية الإعلانات (AnnouncementsView)", min_value=0, max_value=100, value=10)
    discussion = st.number_input("المشاركة في النقاشات (Discussion)", min_value=0, max_value=100, value=10)
    student_absence = st.selectbox("أيام الغياب (StudentAbsenceDays)", ["Under-7", "Above-7"])

with col2:
    nationality = st.selectbox("الجنسية (Nationality)",
                               ["Iran", "Iraq", "Jordan", "KW", "Lybia", "Morocco",
                                "Palestine", "SaudiArabia", "Syria", "Tunis", "USA", "lebanon", "venzuela"])

    stage = st.selectbox("المرحلة الدراسية (StageID)", ["lowerlevel", "MiddleSchool", "HighSchool"])

    grade = st.selectbox("الصف (GradeID)", ["G-04", "G-05", "G-06", "G-07", "G-08", "G-09", "G-10", "G-11", "G-12"])

    section = st.selectbox("الشعبة (SectionID)", ["A", "B", "C"])

    topic = st.selectbox("المادة (Topic)",
                         ["Biology", "Chemistry", "English", "French", "Geology",
                          "History", "IT", "Math", "Quran", "Science", "Spanish"])

    relation = st.selectbox("ولي الأمر المسؤول (Relation)", ["Father", "Mum"])
    parent_survey = st.selectbox("إجابة ولي الأمر على الاستبيان (ParentAnsweringSurvey)", ["Yes", "No"])
    parent_sat = st.selectbox("رضا ولي الأمر (ParentschoolSatisfaction)", ["Good", "Bad"])

# 4. تحويل المدخلات إلى Vector بنفس الـ 60 Feature المتوقعة للموديل
def prepare_features():
    # قائمة الـ 60 ميزة كما هي في الموديل
    feature_names = [
        'gender', 'raisedhands', 'VisITedResources', 'AnnouncementsView', 'Discussion',
        'NationalITy_Iran', 'NationalITy_Iraq', 'NationalITy_Jordan', 'NationalITy_KW',
        'NationalITy_Lybia', 'NationalITy_Morocco', 'NationalITy_Palestine',
        'NationalITy_SaudiArabia', 'NationalITy_Syria', 'NationalITy_Tunis',
        'NationalITy_USA', 'NationalITy_lebanon', 'NationalITy_venzuela',
        'PlaceofBirth_Iran', 'PlaceofBirth_Iraq', 'PlaceofBirth_Jordan',
        'PlaceofBirth_KuwaIT', 'PlaceofBirth_Lybia', 'PlaceofBirth_Morocco',
        'PlaceofBirth_Palestine', 'PlaceofBirth_SaudiArabia', 'PlaceofBirth_Syria',
        'PlaceofBirth_Tunis', 'PlaceofBirth_USA', 'PlaceofBirth_lebanon',
        'PlaceofBirth_venzuela', 'StageID_MiddleSchool', 'StageID_lowerlevel',
        'GradeID_G-04', 'GradeID_G-05', 'GradeID_G-06', 'GradeID_G-07',
        'GradeID_G-08', 'GradeID_G-09', 'GradeID_G-10', 'GradeID_G-11',
        'GradeID_G-12', 'SectionID_B', 'SectionID_C', 'Topic_Biology',
        'Topic_Chemistry', 'Topic_English', 'Topic_French', 'Topic_Geology',
        'Topic_History', 'Topic_IT', 'Topic_Math', 'Topic_Quran',
        'Topic_Science', 'Topic_Spanish', 'Semester_S', 'Relation_Mum',
        'ParentAnsweringSurvey_Yes', 'ParentschoolSatisfaction_Good',
        'StudentAbsenceDays_Under-7'
    ]

    # قاموس لإدراج القيم (افتراضياً 0)
    data = {feat: 0 for feat in feature_names}

    # ملء القيم الأعدادية والجنس
    data['gender'] = 1 if gender == "Female" else 0
    data['raisedhands'] = raisedhands
    data['VisITedResources'] = visited_resources
    data['AnnouncementsView'] = announcements_view
    data['Discussion'] = discussion

    # ملء الـ One-Hot Encoded Features
    if f"NationalITy_{nationality}" in data:
        data[f"NationalITy_{nationality}"] = 1
    if f"PlaceofBirth_{nationality}" in data:  # افتراض مكان الميلاد بنفس الجنسية
        data[f"PlaceofBirth_{nationality}"] = 1

    if f"StageID_{stage}" in data:
        data[f"StageID_{stage}"] = 1

    if f"GradeID_{grade}" in data:
        data[f"GradeID_{grade}"] = 1

    if f"SectionID_{section}" in data:
        data[f"SectionID_{section}"] = 1

    if f"Topic_{topic}" in data:
        data[f"Topic_{topic}"] = 1

    data['Relation_Mum'] = 1 if relation == "Mum" else 0
    data['ParentAnsweringSurvey_Yes'] = 1 if parent_survey == "Yes" else 0
    data['ParentschoolSatisfaction_Good'] = 1 if parent_sat == "Good" else 0
    data['StudentAbsenceDays_Under-7'] = 1 if student_absence == "Under-7" else 0

    # تحويل القاموس إلى مصفوفة 2D متناسبة مع scikit-learn
    return np.array([list(data.values())])

# 5. زر التنبؤ
st.markdown("---")
if st.button("🚀 تشغيل الموديل وإخراج النتيجة", use_container_width=True):
    features = prepare_features()

    # إجراء التنبؤ
    prediction = model.predict(features)

    st.success(f"نتيجة التنبؤ للموديل: **{prediction[0]}**")